let Pseudo = 'ShadowX'
let Nieveau = '12'
let Age = '21'
let Score = '4500'
let Pays = 'Maroc'
console.log('Pseudo: ' + Pseudo)
console.log('Niveau: ' + Nieveau)
console.log('Age: ' + Age)
console.log('Score: ' + Score)
console.log('Pays: ' + Pays)