const prompt = require("prompt-sync")();
let Pseudo = prompt("Pseudo:");
let Niveau = prompt("Niveau:");
let Age = prompt("Age:");
let Score = prompt("Score:");
let Pays = prompt("Pays:");
console.log("Pseudo:",Pseudo);
console.log("Niveau:",Niveau);
console.log("Age:",Age);
console.log("Score:",Score);
console.log("Pays:",Pays);